/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateTLSPolicyMapRequest struct for CreateTLSPolicyMapRequest
type CreateTLSPolicyMapRequest struct {
	// custom parameters you find out more about them [here](http://www.postfix.org/postconf.5.html#smtp_tls_policy_maps)
	Parameters *string `json:"parameters,omitempty"`
	// 1 for a active user account 0 for a disabled user account
	Active *float32 `json:"active,omitempty"`
	// the target domain or email address
	Dest *string `json:"dest,omitempty"`
	// the policy
	Policy *string `json:"policy,omitempty"`
}

// NewCreateTLSPolicyMapRequest instantiates a new CreateTLSPolicyMapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTLSPolicyMapRequest() *CreateTLSPolicyMapRequest {
	this := CreateTLSPolicyMapRequest{}
	return &this
}

// NewCreateTLSPolicyMapRequestWithDefaults instantiates a new CreateTLSPolicyMapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTLSPolicyMapRequestWithDefaults() *CreateTLSPolicyMapRequest {
	this := CreateTLSPolicyMapRequest{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *CreateTLSPolicyMapRequest) GetParameters() string {
	if o == nil || o.Parameters == nil {
		var ret string
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTLSPolicyMapRequest) GetParametersOk() (*string, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *CreateTLSPolicyMapRequest) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given string and assigns it to the Parameters field.
func (o *CreateTLSPolicyMapRequest) SetParameters(v string) {
	o.Parameters = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CreateTLSPolicyMapRequest) GetActive() float32 {
	if o == nil || o.Active == nil {
		var ret float32
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTLSPolicyMapRequest) GetActiveOk() (*float32, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CreateTLSPolicyMapRequest) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given float32 and assigns it to the Active field.
func (o *CreateTLSPolicyMapRequest) SetActive(v float32) {
	o.Active = &v
}

// GetDest returns the Dest field value if set, zero value otherwise.
func (o *CreateTLSPolicyMapRequest) GetDest() string {
	if o == nil || o.Dest == nil {
		var ret string
		return ret
	}
	return *o.Dest
}

// GetDestOk returns a tuple with the Dest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTLSPolicyMapRequest) GetDestOk() (*string, bool) {
	if o == nil || o.Dest == nil {
		return nil, false
	}
	return o.Dest, true
}

// HasDest returns a boolean if a field has been set.
func (o *CreateTLSPolicyMapRequest) HasDest() bool {
	if o != nil && o.Dest != nil {
		return true
	}

	return false
}

// SetDest gets a reference to the given string and assigns it to the Dest field.
func (o *CreateTLSPolicyMapRequest) SetDest(v string) {
	o.Dest = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *CreateTLSPolicyMapRequest) GetPolicy() string {
	if o == nil || o.Policy == nil {
		var ret string
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTLSPolicyMapRequest) GetPolicyOk() (*string, bool) {
	if o == nil || o.Policy == nil {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *CreateTLSPolicyMapRequest) HasPolicy() bool {
	if o != nil && o.Policy != nil {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given string and assigns it to the Policy field.
func (o *CreateTLSPolicyMapRequest) SetPolicy(v string) {
	o.Policy = &v
}

func (o CreateTLSPolicyMapRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.Dest != nil {
		toSerialize["dest"] = o.Dest
	}
	if o.Policy != nil {
		toSerialize["policy"] = o.Policy
	}
	return json.Marshal(toSerialize)
}

type NullableCreateTLSPolicyMapRequest struct {
	value *CreateTLSPolicyMapRequest
	isSet bool
}

func (v NullableCreateTLSPolicyMapRequest) Get() *CreateTLSPolicyMapRequest {
	return v.value
}

func (v *NullableCreateTLSPolicyMapRequest) Set(val *CreateTLSPolicyMapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTLSPolicyMapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTLSPolicyMapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTLSPolicyMapRequest(val *CreateTLSPolicyMapRequest) *NullableCreateTLSPolicyMapRequest {
	return &NullableCreateTLSPolicyMapRequest{value: val, isSet: true}
}

func (v NullableCreateTLSPolicyMapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTLSPolicyMapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
