/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// EditDomainAdminUser200Response struct for EditDomainAdminUser200Response
type EditDomainAdminUser200Response struct {
	Type *string `json:"type,omitempty"`
	// contains request object
	Log []interface{} `json:"log,omitempty"`
	Msg []interface{} `json:"msg,omitempty"`
}

// NewEditDomainAdminUser200Response instantiates a new EditDomainAdminUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditDomainAdminUser200Response() *EditDomainAdminUser200Response {
	this := EditDomainAdminUser200Response{}
	return &this
}

// NewEditDomainAdminUser200ResponseWithDefaults instantiates a new EditDomainAdminUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditDomainAdminUser200ResponseWithDefaults() *EditDomainAdminUser200Response {
	this := EditDomainAdminUser200Response{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EditDomainAdminUser200Response) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDomainAdminUser200Response) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EditDomainAdminUser200Response) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EditDomainAdminUser200Response) SetType(v string) {
	o.Type = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *EditDomainAdminUser200Response) GetLog() []interface{} {
	if o == nil || o.Log == nil {
		var ret []interface{}
		return ret
	}
	return o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDomainAdminUser200Response) GetLogOk() ([]interface{}, bool) {
	if o == nil || o.Log == nil {
		return nil, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *EditDomainAdminUser200Response) HasLog() bool {
	if o != nil && o.Log != nil {
		return true
	}

	return false
}

// SetLog gets a reference to the given []interface{} and assigns it to the Log field.
func (o *EditDomainAdminUser200Response) SetLog(v []interface{}) {
	o.Log = v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *EditDomainAdminUser200Response) GetMsg() []interface{} {
	if o == nil || o.Msg == nil {
		var ret []interface{}
		return ret
	}
	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDomainAdminUser200Response) GetMsgOk() ([]interface{}, bool) {
	if o == nil || o.Msg == nil {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *EditDomainAdminUser200Response) HasMsg() bool {
	if o != nil && o.Msg != nil {
		return true
	}

	return false
}

// SetMsg gets a reference to the given []interface{} and assigns it to the Msg field.
func (o *EditDomainAdminUser200Response) SetMsg(v []interface{}) {
	o.Msg = v
}

func (o EditDomainAdminUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Log != nil {
		toSerialize["log"] = o.Log
	}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	return json.Marshal(toSerialize)
}

type NullableEditDomainAdminUser200Response struct {
	value *EditDomainAdminUser200Response
	isSet bool
}

func (v NullableEditDomainAdminUser200Response) Get() *EditDomainAdminUser200Response {
	return v.value
}

func (v *NullableEditDomainAdminUser200Response) Set(val *EditDomainAdminUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEditDomainAdminUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEditDomainAdminUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditDomainAdminUser200Response(val *EditDomainAdminUser200Response) *NullableEditDomainAdminUser200Response {
	return &NullableEditDomainAdminUser200Response{value: val, isSet: true}
}

func (v NullableEditDomainAdminUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditDomainAdminUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
