/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UpdateDomainRequest struct for UpdateDomainRequest
type UpdateDomainRequest struct {
	Attr *UpdateDomainRequestAttr `json:"attr,omitempty"`
	// contains list of domain names you want update
	Items []string `json:"items,omitempty"`
}

// NewUpdateDomainRequest instantiates a new UpdateDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainRequest() *UpdateDomainRequest {
	this := UpdateDomainRequest{}
	return &this
}

// NewUpdateDomainRequestWithDefaults instantiates a new UpdateDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainRequestWithDefaults() *UpdateDomainRequest {
	this := UpdateDomainRequest{}
	return &this
}

// GetAttr returns the Attr field value if set, zero value otherwise.
func (o *UpdateDomainRequest) GetAttr() UpdateDomainRequestAttr {
	if o == nil || o.Attr == nil {
		var ret UpdateDomainRequestAttr
		return ret
	}
	return *o.Attr
}

// GetAttrOk returns a tuple with the Attr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainRequest) GetAttrOk() (*UpdateDomainRequestAttr, bool) {
	if o == nil || o.Attr == nil {
		return nil, false
	}
	return o.Attr, true
}

// HasAttr returns a boolean if a field has been set.
func (o *UpdateDomainRequest) HasAttr() bool {
	if o != nil && o.Attr != nil {
		return true
	}

	return false
}

// SetAttr gets a reference to the given UpdateDomainRequestAttr and assigns it to the Attr field.
func (o *UpdateDomainRequest) SetAttr(v UpdateDomainRequestAttr) {
	o.Attr = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *UpdateDomainRequest) GetItems() []string {
	if o == nil || o.Items == nil {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainRequest) GetItemsOk() ([]string, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *UpdateDomainRequest) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *UpdateDomainRequest) SetItems(v []string) {
	o.Items = v
}

func (o UpdateDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Attr != nil {
		toSerialize["attr"] = o.Attr
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateDomainRequest struct {
	value *UpdateDomainRequest
	isSet bool
}

func (v NullableUpdateDomainRequest) Get() *UpdateDomainRequest {
	return v.value
}

func (v *NullableUpdateDomainRequest) Set(val *UpdateDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainRequest(val *UpdateDomainRequest) *NullableUpdateDomainRequest {
	return &NullableUpdateDomainRequest{value: val, isSet: true}
}

func (v NullableUpdateDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
