/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeleteAliasRequest struct for DeleteAliasRequest
type DeleteAliasRequest struct {
	// contains list of ids of aliases you want to delete
	Items []string `json:"items,omitempty"`
}

// NewDeleteAliasRequest instantiates a new DeleteAliasRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAliasRequest() *DeleteAliasRequest {
	this := DeleteAliasRequest{}
	return &this
}

// NewDeleteAliasRequestWithDefaults instantiates a new DeleteAliasRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAliasRequestWithDefaults() *DeleteAliasRequest {
	this := DeleteAliasRequest{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DeleteAliasRequest) GetItems() []string {
	if o == nil || o.Items == nil {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteAliasRequest) GetItemsOk() ([]string, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DeleteAliasRequest) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *DeleteAliasRequest) SetItems(v []string) {
	o.Items = v
}

func (o DeleteAliasRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteAliasRequest struct {
	value *DeleteAliasRequest
	isSet bool
}

func (v NullableDeleteAliasRequest) Get() *DeleteAliasRequest {
	return v.value
}

func (v *NullableDeleteAliasRequest) Set(val *DeleteAliasRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAliasRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAliasRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAliasRequest(val *DeleteAliasRequest) *NullableDeleteAliasRequest {
	return &NullableDeleteAliasRequest{value: val, isSet: true}
}

func (v NullableDeleteAliasRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAliasRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
