/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateDomainRequest struct for CreateDomainRequest
type CreateDomainRequest struct {
	// is domain active or not
	Active *bool `json:"active,omitempty"`
	// limit count of aliases associated with this domain
	Aliases *float32 `json:"aliases,omitempty"`
	// relay domain or not
	Backupmx *bool `json:"backupmx,omitempty"`
	// predefined mailbox quota in `add mailbox` form
	Defquota *float32 `json:"defquota,omitempty"`
	// Description of domain
	Description *string `json:"description,omitempty"`
	// Fully qualified domain name
	Domain *string `json:"domain,omitempty"`
	// is domain global address list active or not, it enables shared contacts accross domain in SOGo webmail
	Gal *bool `json:"gal,omitempty"`
	// limit count of mailboxes associated with this domain
	Mailboxes *float32 `json:"mailboxes,omitempty"`
	// maximum quota per mailbox
	Maxquota *float32 `json:"maxquota,omitempty"`
	// maximum quota for this domain (for all mailboxes in sum)
	Quota *float32 `json:"quota,omitempty"`
	// restart SOGo to activate the domain in SOGo
	RestartSogo *float32 `json:"restart_sogo,omitempty"`
	// if not, them you have to create \"dummy\" mailbox for each address to relay
	RelayAllRecipients *bool `json:"relay_all_recipients,omitempty"`
	// Relay non-existing mailboxes only. Existing mailboxes will be delivered locally.
	RelayUnknownOnly *bool   `json:"relay_unknown_only,omitempty"`
	RlFrame          *string `json:"rl_frame,omitempty"`
	// rate limit value
	RlValue *float32 `json:"rl_value,omitempty"`
	// tags for this Domain
	Tags []string `json:"tags,omitempty"`
}

// NewCreateDomainRequest instantiates a new CreateDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDomainRequest() *CreateDomainRequest {
	this := CreateDomainRequest{}
	return &this
}

// NewCreateDomainRequestWithDefaults instantiates a new CreateDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDomainRequestWithDefaults() *CreateDomainRequest {
	this := CreateDomainRequest{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *CreateDomainRequest) SetActive(v bool) {
	o.Active = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetAliases() float32 {
	if o == nil || o.Aliases == nil {
		var ret float32
		return ret
	}
	return *o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetAliasesOk() (*float32, bool) {
	if o == nil || o.Aliases == nil {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasAliases() bool {
	if o != nil && o.Aliases != nil {
		return true
	}

	return false
}

// SetAliases gets a reference to the given float32 and assigns it to the Aliases field.
func (o *CreateDomainRequest) SetAliases(v float32) {
	o.Aliases = &v
}

// GetBackupmx returns the Backupmx field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetBackupmx() bool {
	if o == nil || o.Backupmx == nil {
		var ret bool
		return ret
	}
	return *o.Backupmx
}

// GetBackupmxOk returns a tuple with the Backupmx field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetBackupmxOk() (*bool, bool) {
	if o == nil || o.Backupmx == nil {
		return nil, false
	}
	return o.Backupmx, true
}

// HasBackupmx returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasBackupmx() bool {
	if o != nil && o.Backupmx != nil {
		return true
	}

	return false
}

// SetBackupmx gets a reference to the given bool and assigns it to the Backupmx field.
func (o *CreateDomainRequest) SetBackupmx(v bool) {
	o.Backupmx = &v
}

// GetDefquota returns the Defquota field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetDefquota() float32 {
	if o == nil || o.Defquota == nil {
		var ret float32
		return ret
	}
	return *o.Defquota
}

// GetDefquotaOk returns a tuple with the Defquota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetDefquotaOk() (*float32, bool) {
	if o == nil || o.Defquota == nil {
		return nil, false
	}
	return o.Defquota, true
}

// HasDefquota returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasDefquota() bool {
	if o != nil && o.Defquota != nil {
		return true
	}

	return false
}

// SetDefquota gets a reference to the given float32 and assigns it to the Defquota field.
func (o *CreateDomainRequest) SetDefquota(v float32) {
	o.Defquota = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateDomainRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *CreateDomainRequest) SetDomain(v string) {
	o.Domain = &v
}

// GetGal returns the Gal field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetGal() bool {
	if o == nil || o.Gal == nil {
		var ret bool
		return ret
	}
	return *o.Gal
}

// GetGalOk returns a tuple with the Gal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetGalOk() (*bool, bool) {
	if o == nil || o.Gal == nil {
		return nil, false
	}
	return o.Gal, true
}

// HasGal returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasGal() bool {
	if o != nil && o.Gal != nil {
		return true
	}

	return false
}

// SetGal gets a reference to the given bool and assigns it to the Gal field.
func (o *CreateDomainRequest) SetGal(v bool) {
	o.Gal = &v
}

// GetMailboxes returns the Mailboxes field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetMailboxes() float32 {
	if o == nil || o.Mailboxes == nil {
		var ret float32
		return ret
	}
	return *o.Mailboxes
}

// GetMailboxesOk returns a tuple with the Mailboxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetMailboxesOk() (*float32, bool) {
	if o == nil || o.Mailboxes == nil {
		return nil, false
	}
	return o.Mailboxes, true
}

// HasMailboxes returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasMailboxes() bool {
	if o != nil && o.Mailboxes != nil {
		return true
	}

	return false
}

// SetMailboxes gets a reference to the given float32 and assigns it to the Mailboxes field.
func (o *CreateDomainRequest) SetMailboxes(v float32) {
	o.Mailboxes = &v
}

// GetMaxquota returns the Maxquota field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetMaxquota() float32 {
	if o == nil || o.Maxquota == nil {
		var ret float32
		return ret
	}
	return *o.Maxquota
}

// GetMaxquotaOk returns a tuple with the Maxquota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetMaxquotaOk() (*float32, bool) {
	if o == nil || o.Maxquota == nil {
		return nil, false
	}
	return o.Maxquota, true
}

// HasMaxquota returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasMaxquota() bool {
	if o != nil && o.Maxquota != nil {
		return true
	}

	return false
}

// SetMaxquota gets a reference to the given float32 and assigns it to the Maxquota field.
func (o *CreateDomainRequest) SetMaxquota(v float32) {
	o.Maxquota = &v
}

// GetQuota returns the Quota field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetQuota() float32 {
	if o == nil || o.Quota == nil {
		var ret float32
		return ret
	}
	return *o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetQuotaOk() (*float32, bool) {
	if o == nil || o.Quota == nil {
		return nil, false
	}
	return o.Quota, true
}

// HasQuota returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasQuota() bool {
	if o != nil && o.Quota != nil {
		return true
	}

	return false
}

// SetQuota gets a reference to the given float32 and assigns it to the Quota field.
func (o *CreateDomainRequest) SetQuota(v float32) {
	o.Quota = &v
}

// GetRestartSogo returns the RestartSogo field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetRestartSogo() float32 {
	if o == nil || o.RestartSogo == nil {
		var ret float32
		return ret
	}
	return *o.RestartSogo
}

// GetRestartSogoOk returns a tuple with the RestartSogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetRestartSogoOk() (*float32, bool) {
	if o == nil || o.RestartSogo == nil {
		return nil, false
	}
	return o.RestartSogo, true
}

// HasRestartSogo returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasRestartSogo() bool {
	if o != nil && o.RestartSogo != nil {
		return true
	}

	return false
}

// SetRestartSogo gets a reference to the given float32 and assigns it to the RestartSogo field.
func (o *CreateDomainRequest) SetRestartSogo(v float32) {
	o.RestartSogo = &v
}

// GetRelayAllRecipients returns the RelayAllRecipients field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetRelayAllRecipients() bool {
	if o == nil || o.RelayAllRecipients == nil {
		var ret bool
		return ret
	}
	return *o.RelayAllRecipients
}

// GetRelayAllRecipientsOk returns a tuple with the RelayAllRecipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetRelayAllRecipientsOk() (*bool, bool) {
	if o == nil || o.RelayAllRecipients == nil {
		return nil, false
	}
	return o.RelayAllRecipients, true
}

// HasRelayAllRecipients returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasRelayAllRecipients() bool {
	if o != nil && o.RelayAllRecipients != nil {
		return true
	}

	return false
}

// SetRelayAllRecipients gets a reference to the given bool and assigns it to the RelayAllRecipients field.
func (o *CreateDomainRequest) SetRelayAllRecipients(v bool) {
	o.RelayAllRecipients = &v
}

// GetRelayUnknownOnly returns the RelayUnknownOnly field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetRelayUnknownOnly() bool {
	if o == nil || o.RelayUnknownOnly == nil {
		var ret bool
		return ret
	}
	return *o.RelayUnknownOnly
}

// GetRelayUnknownOnlyOk returns a tuple with the RelayUnknownOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetRelayUnknownOnlyOk() (*bool, bool) {
	if o == nil || o.RelayUnknownOnly == nil {
		return nil, false
	}
	return o.RelayUnknownOnly, true
}

// HasRelayUnknownOnly returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasRelayUnknownOnly() bool {
	if o != nil && o.RelayUnknownOnly != nil {
		return true
	}

	return false
}

// SetRelayUnknownOnly gets a reference to the given bool and assigns it to the RelayUnknownOnly field.
func (o *CreateDomainRequest) SetRelayUnknownOnly(v bool) {
	o.RelayUnknownOnly = &v
}

// GetRlFrame returns the RlFrame field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetRlFrame() string {
	if o == nil || o.RlFrame == nil {
		var ret string
		return ret
	}
	return *o.RlFrame
}

// GetRlFrameOk returns a tuple with the RlFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetRlFrameOk() (*string, bool) {
	if o == nil || o.RlFrame == nil {
		return nil, false
	}
	return o.RlFrame, true
}

// HasRlFrame returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasRlFrame() bool {
	if o != nil && o.RlFrame != nil {
		return true
	}

	return false
}

// SetRlFrame gets a reference to the given string and assigns it to the RlFrame field.
func (o *CreateDomainRequest) SetRlFrame(v string) {
	o.RlFrame = &v
}

// GetRlValue returns the RlValue field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetRlValue() float32 {
	if o == nil || o.RlValue == nil {
		var ret float32
		return ret
	}
	return *o.RlValue
}

// GetRlValueOk returns a tuple with the RlValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetRlValueOk() (*float32, bool) {
	if o == nil || o.RlValue == nil {
		return nil, false
	}
	return o.RlValue, true
}

// HasRlValue returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasRlValue() bool {
	if o != nil && o.RlValue != nil {
		return true
	}

	return false
}

// SetRlValue gets a reference to the given float32 and assigns it to the RlValue field.
func (o *CreateDomainRequest) SetRlValue(v float32) {
	o.RlValue = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateDomainRequest) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDomainRequest) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateDomainRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateDomainRequest) SetTags(v []string) {
	o.Tags = v
}

func (o CreateDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.Aliases != nil {
		toSerialize["aliases"] = o.Aliases
	}
	if o.Backupmx != nil {
		toSerialize["backupmx"] = o.Backupmx
	}
	if o.Defquota != nil {
		toSerialize["defquota"] = o.Defquota
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	if o.Gal != nil {
		toSerialize["gal"] = o.Gal
	}
	if o.Mailboxes != nil {
		toSerialize["mailboxes"] = o.Mailboxes
	}
	if o.Maxquota != nil {
		toSerialize["maxquota"] = o.Maxquota
	}
	if o.Quota != nil {
		toSerialize["quota"] = o.Quota
	}
	if o.RestartSogo != nil {
		toSerialize["restart_sogo"] = o.RestartSogo
	}
	if o.RelayAllRecipients != nil {
		toSerialize["relay_all_recipients"] = o.RelayAllRecipients
	}
	if o.RelayUnknownOnly != nil {
		toSerialize["relay_unknown_only"] = o.RelayUnknownOnly
	}
	if o.RlFrame != nil {
		toSerialize["rl_frame"] = o.RlFrame
	}
	if o.RlValue != nil {
		toSerialize["rl_value"] = o.RlValue
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableCreateDomainRequest struct {
	value *CreateDomainRequest
	isSet bool
}

func (v NullableCreateDomainRequest) Get() *CreateDomainRequest {
	return v.value
}

func (v *NullableCreateDomainRequest) Set(val *CreateDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDomainRequest(val *CreateDomainRequest) *NullableCreateDomainRequest {
	return &NullableCreateDomainRequest{value: val, isSet: true}
}

func (v NullableCreateDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
