/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeleteDKIMKeyRequest struct for DeleteDKIMKeyRequest
type DeleteDKIMKeyRequest struct {
	// contains list of ids of domains you want to delete DKIM keys for
	Items []string `json:"items,omitempty"`
}

// NewDeleteDKIMKeyRequest instantiates a new DeleteDKIMKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDKIMKeyRequest() *DeleteDKIMKeyRequest {
	this := DeleteDKIMKeyRequest{}
	return &this
}

// NewDeleteDKIMKeyRequestWithDefaults instantiates a new DeleteDKIMKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDKIMKeyRequestWithDefaults() *DeleteDKIMKeyRequest {
	this := DeleteDKIMKeyRequest{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *DeleteDKIMKeyRequest) GetItems() []string {
	if o == nil || o.Items == nil {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteDKIMKeyRequest) GetItemsOk() ([]string, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *DeleteDKIMKeyRequest) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *DeleteDKIMKeyRequest) SetItems(v []string) {
	o.Items = v
}

func (o DeleteDKIMKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteDKIMKeyRequest struct {
	value *DeleteDKIMKeyRequest
	isSet bool
}

func (v NullableDeleteDKIMKeyRequest) Get() *DeleteDKIMKeyRequest {
	return v.value
}

func (v *NullableDeleteDKIMKeyRequest) Set(val *DeleteDKIMKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDKIMKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDKIMKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDKIMKeyRequest(val *DeleteDKIMKeyRequest) *NullableDeleteDKIMKeyRequest {
	return &NullableDeleteDKIMKeyRequest{value: val, isSet: true}
}

func (v NullableDeleteDKIMKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDKIMKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
