/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CreateOAuthClientRequest struct for CreateOAuthClientRequest
type CreateOAuthClientRequest struct {
	// the uri where you should be redirected after oAuth
	RedirectUri *string `json:"redirect_uri,omitempty"`
}

// NewCreateOAuthClientRequest instantiates a new CreateOAuthClientRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOAuthClientRequest() *CreateOAuthClientRequest {
	this := CreateOAuthClientRequest{}
	return &this
}

// NewCreateOAuthClientRequestWithDefaults instantiates a new CreateOAuthClientRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOAuthClientRequestWithDefaults() *CreateOAuthClientRequest {
	this := CreateOAuthClientRequest{}
	return &this
}

// GetRedirectUri returns the RedirectUri field value if set, zero value otherwise.
func (o *CreateOAuthClientRequest) GetRedirectUri() string {
	if o == nil || o.RedirectUri == nil {
		var ret string
		return ret
	}
	return *o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOAuthClientRequest) GetRedirectUriOk() (*string, bool) {
	if o == nil || o.RedirectUri == nil {
		return nil, false
	}
	return o.RedirectUri, true
}

// HasRedirectUri returns a boolean if a field has been set.
func (o *CreateOAuthClientRequest) HasRedirectUri() bool {
	if o != nil && o.RedirectUri != nil {
		return true
	}

	return false
}

// SetRedirectUri gets a reference to the given string and assigns it to the RedirectUri field.
func (o *CreateOAuthClientRequest) SetRedirectUri(v string) {
	o.RedirectUri = &v
}

func (o CreateOAuthClientRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RedirectUri != nil {
		toSerialize["redirect_uri"] = o.RedirectUri
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOAuthClientRequest struct {
	value *CreateOAuthClientRequest
	isSet bool
}

func (v NullableCreateOAuthClientRequest) Get() *CreateOAuthClientRequest {
	return v.value
}

func (v *NullableCreateOAuthClientRequest) Set(val *CreateOAuthClientRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOAuthClientRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOAuthClientRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOAuthClientRequest(val *CreateOAuthClientRequest) *NullableCreateOAuthClientRequest {
	return &NullableCreateOAuthClientRequest{value: val, isSet: true}
}

func (v NullableCreateOAuthClientRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOAuthClientRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
