/*
mailcow API

mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DeleteForwardHostRequest struct for DeleteForwardHostRequest
type DeleteForwardHostRequest struct {
	// contains the ip of the fowarding host you want to delete
	Ip *string `json:"ip,omitempty"`
}

// NewDeleteForwardHostRequest instantiates a new DeleteForwardHostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteForwardHostRequest() *DeleteForwardHostRequest {
	this := DeleteForwardHostRequest{}
	return &this
}

// NewDeleteForwardHostRequestWithDefaults instantiates a new DeleteForwardHostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteForwardHostRequestWithDefaults() *DeleteForwardHostRequest {
	this := DeleteForwardHostRequest{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *DeleteForwardHostRequest) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteForwardHostRequest) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *DeleteForwardHostRequest) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *DeleteForwardHostRequest) SetIp(v string) {
	o.Ip = &v
}

func (o DeleteForwardHostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteForwardHostRequest struct {
	value *DeleteForwardHostRequest
	isSet bool
}

func (v NullableDeleteForwardHostRequest) Get() *DeleteForwardHostRequest {
	return v.value
}

func (v *NullableDeleteForwardHostRequest) Set(val *DeleteForwardHostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteForwardHostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteForwardHostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteForwardHostRequest(val *DeleteForwardHostRequest) *NullableDeleteForwardHostRequest {
	return &NullableDeleteForwardHostRequest{value: val, isSet: true}
}

func (v NullableDeleteForwardHostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteForwardHostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
